* Numerical Methods and Optimisation in Finance @@html:<img alt="CRAN/METACRAN" src="https://img.shields.io/cran/v/NMOF">@@

  Functions, examples and data from the first and the
  second edition of "Numerical Methods and Optimization
  in Finance" by [[http://www.unige.ch/ses/dsec/static/gilli/][M. Gilli]], [[https://wwz.unibas.ch/de/personen/dietmar-maringer/][D. Maringer]] and [[http://enricoschumann.net/][E. Schumann]]
  (2019, ISBN:978-0128150658).  The package provides
  implementations of optimisation heuristics
  (Differential Evolution, Genetic Algorithms, Particle
  Swarm Optimisation, Simulated Annealing and Threshold
  Accepting), and other optimisation tools, such as
  grid search and greedy search.  There are also
  functions for the valuation of financial instruments,
  such as bonds and options, and functions that help
  with stochastic simulations.

** Installing the package

   The latest build of the package is always available from
   [[http://enricoschumann.net/R/packages/NMOF/]]. A
   stable version is available from [[https://cran.r-project.org/package=NMOF][CRAN]].

   To install the package from within an R session, type:
#+BEGIN_SRC R :eval never :export code
install.packages('NMOF')  ## CRAN version
install.packages('NMOF',  ## development version
                 repos = c('http://enricoschumann.net/R',
                           getOption('repos')))
#+END_SRC


** News, feedback and discussion

   New package releases and other news related to the book or the
   package are announced on the [[https://lists.r-forge.r-project.org/cgi-bin/mailman/listinfo/nmof-news][NMOF-news mailing list]].

   An [[http://enricoschumann.net/R/packages/NMOF/NMOF_news.xml][RSS feed of the package NEWS file]] is also available.

   Applications, as long as they are finance-related, should be
   discussed on the [[https://stat.ethz.ch/mailman/listinfo/r-sig-finance][R-SIG-Finance mailing list]].

   Please send bug reports or suggestions directly to the
   package maintainer, for instance by using =bug.report=.

#+BEGIN_SRC R :eval never :export code
require("utils")
bug.report("[NMOF] Unexpected behaviour in function XXX",
           maintainer("NMOF"), package = "NMOF")
#+END_SRC



** References

   Manfred Gilli, Dietmar Maringer and Enrico Schumann.
   [[https://www.amazon.com/-/de/Numerical-Methods-Optimization-Finance-Manfred/dp/0128150653][Numerical Methods and Optimization in Finance]]. Academic
   Press, 2019.
