* Numerical Methods and Optimisation in Finance

  The NMOF package provides many of the code examples and
  data sets used in the book "Numerical Methods and
  Optimization in Finance" by [[http://www.unige.ch/ses/dsec/static/gilli/][M. Gilli]], [[https://wwz.unibas.ch/personen/profil/person/maringer/][D. Maringer]] and
  [[http://enricoschumann.net/][E. Schumann]] (2011), ISBN 978-0123756626. The package also
  contains several functions that have not been described in
  the book. Notably, the package provides implementations of
  a number of optimisation heuristics, among them
  Differential Evolution and Genetic Algorithms. There are
  also functions for valuing financial instruments such as
  bonds and options, and helper functions for stochastic
  simulations.

** Installing the package

   The latest build of the package is always available from
   [[http://enricoschumann.net/R/packages/NMOF/index.htm]]. A
   stable version is available from [[https://cran.r-project.org/web/packages/NMOF/index.html][CRAN]].

   To install the package from within an R session, type:
#+BEGIN_SRC R :eval never :export code
install.packages('NMOF')  ## CRAN version
install.packages('NMOF', type = 'source',
                 repos = c('http://enricoschumann.net/R', getOption('repos')))
#+END_SRC


** News, feedback and discussion

   New package releases and other news related to the book or the
   package are announced on the [[https://lists.r-forge.r-project.org/cgi-bin/mailman/listinfo/nmof-news][NMOF-news mailing list]].

   An [[http://enricoschumann.net/R/packages/NMOF/NMOF_news.xml][RSS feed of the package NEWS file]] is also available.
   
   Applications, as long as they are finance-related, should be
   discussed on the [[https://stat.ethz.ch/mailman/listinfo/r-sig-finance][R-SIG-Finance mailing list]].

   Please send bug reports or suggestions directly to the
   package maintainer, for instance by using =bug.report=.

#+BEGIN_SRC R :eval never :export code
require("utils")
bug.report("[NMOF] Unexpected behaviour in function XXX", 
           maintainer("NMOF"), package = "NMOF")
#+END_SRC



** References

   Manfred Gilli, Dietmar Maringer and Enrico Schumann. 
   [[http://www.amazon.com/Numerical-Methods-Optimization-Finance-Manfred/dp/0123756626/][Numerical Methods and Optimization in Finance]]. Academic
   Press, 2011.
